# Identité du projet (doit correspondre à SonarQube)
sonar.projectKey=crud_app
sonar.projectName=crud_app

# Encodage
sonar.sourceEncoding=UTF-8

# Langage
sonar.language=php

# Code source et tests
sonar.sources=app
sonar.tests=tests

# Exclusions (Laravel)
sonar.exclusions=vendor/**,storage/**,bootstrap/**,node_modules/**,public/**,database/**

# Couverture de tests PHPUnit (PCOV → Clover XML)
sonar.php.coverage.reportPaths=build/coverage/coverage.xml